# Generated by Django 4.2.3 on 2023-08-17 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('users', models.ManyToManyField(blank=True, related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sinf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/teachers/<django.db.models.fields.related.OneToOneField>/avatar/%Y_%m_%d')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('id_card', models.CharField(blank=True, max_length=50, null=True)),
                ('sallery_type', models.CharField(choices=[('FIXED', 'fixed'), ('PER_HOURS', 'soatbay')], max_length=255)),
                ('sallery', models.IntegerField(default=0)),
                ('date_of_employment', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Erkak'), ('FEMALE', 'Ayol')], max_length=255)),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('language_certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('lens', models.FileField(blank=True, null=True, upload_to='uploads/teachers/<django.db.models.fields.related.OneToOneField>/lens/%Y_%m_%d')),
                ('id_card_photo', models.FileField(blank=True, null=True, upload_to='uploads/teachers/<django.db.models.fields.related.OneToOneField>/id_card_photo/%Y_%m_%d')),
                ('survey', models.FileField(blank=True, null=True, upload_to='uploads/teachers/<django.db.models.fields.related.OneToOneField>/survey/%Y_%m_%d')),
                ('biography', models.FileField(blank=True, null=True, upload_to='uploads/teachers/<django.db.models.fields.related.OneToOneField>/biography/%Y_%m_%d')),
                ('medical_book', models.FileField(blank=True, null=True, upload_to='uploads/teachers/<django.db.models.fields.related.OneToOneField>/biography/%Y_%m_%d')),
                ('picture_3x4', models.FileField(blank=True, null=True, upload_to='uploads/teachers/<django.db.models.fields.related.OneToOneField>/picture_3x4/%Y_%m_%d')),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='website.science')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/students/<django.db.models.fields.related.OneToOneField>/avatar/%Y_%m_%d')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('id_card', models.CharField(max_length=50)),
                ('date_of_admission', models.DateField(blank=True, null=True)),
                ('id_card_parents', models.FileField(blank=True, null=True, upload_to='uploads/students/<django.db.models.fields.related.OneToOneField>/id_card_parents/%Y_%m_%d')),
                ('picture_3x4', models.FileField(blank=True, null=True, upload_to='uploads/students/<django.db.models.fields.related.OneToOneField>/picture_3x4/%Y_%m_%d')),
                ('school_tab', models.FileField(blank=True, null=True, upload_to='uploads/students/<django.db.models.fields.related.OneToOneField>/picture_3x4/%Y_%m_%d')),
                ('class_of_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='website.sinf')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sinf',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinflar', to='website.teacher'),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/avatar/%Y_%m_%d')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='website.student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('file_message', models.FileField(blank=True, null=True, upload_to='uploads/message/%Y_%m_%d')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='website.chat_room')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_messages', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menus', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/avatar/%Y_%m_%d')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('lavozim', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Davomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('davomat', models.CharField(choices=[('SABABLI', 'Sababli'), ('SABABSIZ', 'Sababsiz'), ('KELGAN', 'kelgan')], max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davomatlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Davomatlar',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/avatar/%Y_%m_%d')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('permission', models.ManyToManyField(blank=True, related_name='admins', to='website.permission')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='website.type_of_admin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
