# Generated by Django 4.2.3 on 2023-08-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_student_class_of_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='permission',
            new_name='permissions',
        ),
    ]
