# Generated by Django 4.2.3 on 2023-08-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_delete_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='language_certificate',
            field=models.FileField(blank=True, null=True, upload_to='uploads/teachers/<django.db.models.fields.related.OneToOneField>/l_sert/%Y_%m_%d'),
        ),
    ]
