# Generated by Django 4.2.3 on 2023-08-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='davomat',
            name='sabab',
            field=models.TextField(blank=True, null=True),
        ),
    ]
