# Generated by Django 4.2.3 on 2023-08-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_davomat_sabab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='sallery',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employer',
            name='sallery',
            field=models.IntegerField(default=0),
        ),
    ]
