# Generated by Django 4.2.3 on 2023-08-31 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_expense_admin_sallery_employer_sallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='sallery',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='sallery',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='sallery',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='sallery_type',
            new_name='salary_type',
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
