# Generated by Django 4.2.4 on 2023-09-07 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_teacher_salary_student_parent_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PAID', "to'lagan"), ('NO_PAID', "to'lamagan")], max_length=255, verbose_name='holat:')),
                ('amount', models.IntegerField(default=0, verbose_name='pul miqdori:')),
                ('date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pays', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='pul miqdori:')),
                ('types_finance', models.CharField(choices=[('SALARY', 'oylik maosh'), ('STUDENT_PAY', "o'quvchilar to'lovi"), ('OTHER', 'boshqa')], max_length=60, verbose_name='Chiqim yoki Kirim turi:')),
                ('types', models.CharField(blank=True, choices=[('SALARY', 'oylik maosh'), ('STUDENT_PAY', "o'quvchilar to'lovi"), ('OTHER', 'boshqa')], max_length=60, null=True, verbose_name='(Chiqim,Kirim) turi:')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Chiqim sababi:')),
                ('date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_pays', to='accounts.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='accounts.teacher')),
            ],
        ),
    ]
