# Generated by Django 4.2.4 on 2023-09-12 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_pay',
            name='amount_2',
            field=models.IntegerField(default=-1000),
        ),
        migrations.CreateModel(
            name='Each_Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.IntegerField()),
                ('std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolovlar', to='finance.student_pay')),
            ],
        ),
    ]
