# Generated by Django 4.2.4 on 2023-09-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finance',
            options={'verbose_name_plural': 'Finance'},
        ),
        migrations.AlterModelOptions(
            name='student_pay',
            options={'verbose_name_plural': "O'quvchi To'lovlari"},
        ),
    ]
