# Generated by Django 4.2.4 on 2023-10-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_debt',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
