# Generated by Django 4.2.4 on 2023-09-12 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_student_pay_amount_2_each_pay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='each_pay',
            old_name='std',
            new_name='std_pay',
        ),
    ]
