# Generated by Django 4.2.4 on 2023-09-08 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_teacher_salary_student_parent_employer'),
        ('finance', '0002_alter_finance_options_alter_student_pay_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_pays', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='accounts.teacher'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='types',
            field=models.CharField(blank=True, choices=[('EXPONSE', 'Chiqim'), ('INCOME', 'Kirim')], max_length=60, null=True, verbose_name='(Chiqim,Kirim) turi:'),
        ),
    ]
