# Generated by Django 4.2.4 on 2023-10-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_expense_type_expense_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='student_debt',
            name='status',
        ),
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(blank=True, choices=[('SALARY', 'salary'), ('OTHER', 'other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_debt',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
