# Generated by Django 4.2.4 on 2023-10-28 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_student_debt_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_debt',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
