# Generated by Django 4.2.4 on 2023-10-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_expense_paid_remove_student_debt_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
