# Generated by Django 4.2.4 on 2023-09-12 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_std_each_pay_std_pay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_pay',
            old_name='amount_3',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='student_pay',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='student_pay',
            name='amount_2',
        ),
        migrations.RemoveField(
            model_name='student_pay',
            name='date',
        ),
        migrations.AddField(
            model_name='student_pay',
            name='change_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student_pay',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student_pay',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
