# Generated by Django 4.2.4 on 2023-10-31 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='active',
        ),
    ]
