# Generated by Django 4.2.4 on 2023-10-20 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_teacher_description_and_more'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('begin_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('study_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaskForClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=255)),
                ('task_message', models.TextField()),
                ('complete_to_user', models.BooleanField(default=False)),
                ('complete_from_user', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('begin_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('from_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasksforclass', to='accounts.teacher')),
                ('to_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='school.class')),
            ],
        ),
    ]
