# Generated by Django 4.2.4 on 2023-09-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_student_amount_status'),
        ('school', '0002_teacher_lesson_parent_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parent_Comments',
            new_name='Parent_Comment',
        ),
    ]
