# Generated by Django 4.2.4 on 2023-10-31 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('school', '0002_remove_company_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='accounts.teacher'),
            preserve_default=False,
        ),
    ]
