# Generated by Django 4.2.4 on 2023-09-07 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_teacher_salary_student_parent_employer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0002_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Sinflar'},
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.CharField(choices=[('MONDAY', 'Dushanba'), ('TUESDAY', 'Seshanba'), ('WEDNESDAY', 'Chorshanba'), ('THURSDAY', 'Payshanba'), ('FRIDAY', 'Juma'), ('SATURDAY', 'Shanba')], default='monday', max_length=10)),
                ('lesson_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.lesson_time')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.room')),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.science')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='accounts.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=1)),
                ('grade_datetime', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('SABABLI', 'Sababli'), ('SABABSIZ', 'Sababsiz'), ('KELGAN', 'kelgan')], max_length=50, verbose_name='davomat turi:')),
                ('date', models.DateField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True, verbose_name="sabab(Agar sababli turida bo'lsa):")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davomatlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Davomatlar',
            },
        ),
    ]
