# Generated by Django 4.2.4 on 2023-09-13 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_latest_amount_date'),
        ('school', '0003_rename_parent_comments_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent_comment',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_answers', to='accounts.admin'),
        ),
    ]
