# Generated by Django 4.2.4 on 2023-09-07 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_lesson_time_room_alter_class_options_lesson_grade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name_plural': 'Baholar'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name_plural': 'Darslar'},
        ),
        migrations.AlterModelOptions(
            name='lesson_time',
            options={'verbose_name_plural': 'Dars soatlari'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name_plural': 'Xonalar'},
        ),
        migrations.RemoveField(
            model_name='lesson_time',
            name='name',
        ),
        migrations.AddField(
            model_name='lesson_time',
            name='begin_time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 7, 12, 43, 58, 396758, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson_time',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 7, 12, 44, 12, 446497, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(choices=[(1, 'Bir'), (2, 'Ikki'), (3, 'Uch'), (4, "To'rt"), (5, 'Besh')], default=1),
        ),
    ]
