# Generated by Django 4.2.4 on 2023-09-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_grade_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='student_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.class'),
            preserve_default=False,
        ),
    ]
