# Generated by Django 4.2.4 on 2023-09-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_lesson_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
