# Generated by Django 4.2.4 on 2023-09-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_class_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['lesson_date', 'lesson_time'], 'verbose_name_plural': 'Darslar'},
        ),
    ]
