# Generated by Django 4.2.4 on 2023-09-07 02:49

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_class'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='Oylik maosh(soatbay narx):'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=50)),
                ('date_of_admission', models.DateField(blank=True, null=True)),
                ('id_card_parents', models.FileField(blank=True, null=True, upload_to=accounts.models.Student.student_id_card_parents_path, verbose_name='Ota-ona pasporti nusxasi:')),
                ('picture_3x4', models.FileField(blank=True, null=True, upload_to=accounts.models.Student.student_picture_3x4_path, verbose_name='3x4 rasm:')),
                ('school_tab', models.FileField(blank=True, null=True, upload_to=accounts.models.Student.student_school_tab_path, verbose_name='Maktabdan Tabel asli 2-11-sinflar uchun:')),
                ('medical_book', models.FileField(blank=True, null=True, upload_to=accounts.models.Student.student_medical_book_path, verbose_name='Tibbiy Daftarcha (086):')),
                ('amount', models.IntegerField(default=0, verbose_name='hisobidagi pul miqdori:')),
                ('amount_status', models.CharField(choices=[('PAID', "to'lagan"), ('NO_PAID', "to'lamagan")], max_length=255, verbose_name='hisobidagi pul miqdori turi:')),
                ('class_of_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "O'quvchilar",
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='accounts.student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Otan ona',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(default=0, verbose_name='Oylik maosh:')),
                ('position', models.CharField(max_length=255, verbose_name='Lavozim:')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Xodimlar',
            },
        ),
    ]
