# Generated by Django 4.2.4 on 2023-09-12 04:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.UserProfile.user_avatar_path, verbose_name='Avatar uchun surat:'),
        ),
    ]
