# Generated by Django 4.2.4 on 2023-09-15 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_of_student',
        ),
    ]
