# Generated by Django 4.2.4 on 2023-10-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='student',
            name='amount_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='latest_amount_date',
        ),
    ]
