# Generated by Django 4.2.4 on 2023-09-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='amount_status',
            field=models.CharField(blank=True, choices=[('PAID', "to'lagan"), ('NO_PAID', "to'lamagan")], max_length=255, null=True, verbose_name='hisobidagi pul miqdori turi:'),
        ),
    ]
